# Generated by Django 3.1.1 on 2020-10-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=50)),
                ('weight_uom', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_male', models.BooleanField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.species')),
            ],
        ),
    ]
