# Generated by Django 3.1.1 on 2020-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201013_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='name_text',
        ),
    ]
