# Generated by Django 3.1.1 on 2020-10-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201013_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name_text',
            new_name='name',
        ),
    ]
