# Generated by Django 3.1.1 on 2020-10-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201013_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='species_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='species',
            name='icon',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
