# Generated by Django 3.1.1 on 2020-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201013_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='', upload_to='animals'),
            preserve_default=False,
        ),
    ]
