# Generated by Django 3.1.1 on 2020-10-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='icon',
        ),
    ]
